service: telegram-jira-bot

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    CHAT_ID: ${env:CHAT_ID}

functions:
  listenAndSend:
    handler: handler.listen_and_send
    events:
      - http:
          path: send-to-telegram
          method: post
          cors: true